name: macOS arm64

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [macOS, ARM64]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Resolve Qt Prefix
      id: resolve-qt-prefix
      run: |
        echo "::set-output name=path::$(cd "$GITHUB_WORKSPACE/../" && pwd)/dist"
      shell: bash

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ steps.resolve-qt-prefix.outputs.path }}
        key: qt5-macos-arm64

    - name: Build Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: |
        . tools/macos/activate-env
        get-qt
        build-qt

    - name: Build Cryptoshark
      run: ./build

    - name: Package Cryptoshark
      run: |
        . tools/macos/activate-env
        mkdmg ../build-cryptoshark-arm64

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest-macos-arm64
        prerelease: true
        title: Latest macOS Build for arm64
        files: |
          ../build-cryptoshark-arm64/*.dmg
