name: macOS x86_64

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Resolve Qt Prefix
      id: resolve-qt-prefix
      run: |
        echo "::set-output name=path::$(cd "$GITHUB_WORKSPACE/../" && pwd)/dist"
      shell: bash

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ steps.resolve-qt-prefix.outputs.path }}
        key: qt-macos-10.15-x86_64

    - name: Build Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: |
        . tools/macos/activate-env
        get-qt
        build-qt

    - name: Build Cryptoshark
      run: |
        . tools/macos/activate-env
        ./build
        macdeployqt ../build-cryptoshark-x86_64/app/Cryptoshark.app -dmg

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest-macos-x86_64
        prerelease: true
        title: Latest macOS Build for x86_64
        files: |
          ../build-cryptoshark-x86_64/app/Cryptoshark.dmg
